name: Docker Image CI
      
on:
  push:
    branches:
    - cicd-1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.CI_REGISTRY }}${{ github.repository }}/
      IMAGE_NAME: ${{ github.ref_name }}:${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
    - run: echo '${{ toJSON(github) }}'
    - run: echo "image name $(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')"
    - run: echo "image name $(echo "$REGISTRY_URL$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')"
    - name: Build and push the Docker image
      run: |
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        DOCKER_BUILDKIT=1 docker build -t $(echo "$REGISTRY_URL$IMAGE_NAME" | tr '[:upper:]' '[:lower:]') .
        docker push $(echo "$REGISTRY_URL$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
