name: Docker Image CI
      
on:
  push:
    branches:
    - cicd-1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: $GITHUB_REF_NAME:$GITHUB_SHA
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        DOCKER_BUILDKIT=1 docker build --target prod -t $IMAGE_NAME .
        docker push $IMAGE_NAME
