name: Docker Image CI
      
on:
  push:
    branches:
    - cicd-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        DOCKER_BUILDKIT=1 docker build --target prod -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
